### PR TITLE
Port to GTK+3

### PR DESCRIPTION
**Pull request by Aniket21mathur**
The activity was not in GTK+3.

Now porting the activity to GTK+3.The files changed include:
-activity.py
-setup.py
-activty/activity.info

Fixes https://github.com/sugarlabs/sin-dientes-activity/issues/1

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@quozl Can you please have a look into it.Thanks!

**Comment by quozl** [comment]
Thanks.  Please continue; the activity canvas is very different after these changes, and things move around, so I'm guessing you are yet to finish.  See also our [GTK+ 3 Porting Guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/gtk3-porting-guide.md).

**Comment by yashagrawal3** [comment]
Thanks, reviewed and tested. It seems to work fine on my setup, so probably this is due to testing this activity on different platforms.
@Aniket21mathur please tell me the platform you are testing, including Sugar version, Ubuntu/Debian version and whether you are running it on VirtualBox. 
Hello @quozl , can you please tell the same, so that we can figure it out.

Here is screenshot comparison of master vs Issue1(@Aniket21mathur) on my system:
-----------------------------------------------------------------------------
Master:
mas1
Issue1:
iss1
-----------------------------------------------------------------------------
Master:
mas2
Issue1:
iss2
-----------------------------------------------------------------------------
Master:
mas3
Issue1:
iss3
----------------------------------------------------------------------------------

All them appear to be function alright also, @quozl please review! :)

**Comment by Aniket21mathur** [comment]
Thanks @yashagrawal3.I am using Ubuntu 18.04 on an oracle virtual machine.
@quozl the size of the rectangle is changed whenever the text content under "Pista" label is large.So I set the max characters limit  after which wrapping happens.This fixed the problem.
Thanks!

**Comment by quozl** [comment]
Thanks.  Reviewed.  Tested.  Works fine.  I'm ready to merge, but will wait for @yashagrawal3 to answer.  (consensus seeking within those who are on the thread).

**Comment by yashagrawal3** [comment]
Reviewed and tested, looks good to go.

**Pull request merged**
