### PR TITLE
Adding categories to resources

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Categories were hard coded in the python code.

Making a new file in resources "categoria.palabra" having names of
categories and importing names from that file.

Fixes https://github.com/sugarlabs/sin-dientes-activity/issues/2

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Comments;
* [ ] remove the `_()` translation function; the translation team cannot translate variables, and the resources files will eventually be language specific,
* [ ] are the quotation marks needed?  I see they are removed by `replace()`
* [ ] is the missing end-of-line marker in the file important?

**Comment by quozl** [comment]
It was like that before though.

**Comment by pro-panda** [comment]
> The improvement now is that changing a title and word list requires no code changes.

Agreed

**Comment by quozl** [comment]
@Aniket21mathur, what do you think?

By adding the titles to a separate file, that means changing a word list steps are;
* edit `resources/nivel*.palabra`,
* edit `resources/categoria.palabra`.

An alternative may be to use the first line of a word list as the category name.  Then only one file is edited.

Adding a new word list is indeed complicated by the assumption in the code of the number of levels.

**Comment by quozl** [comment]
@Aniket21mathur, what do you want to do?

Yes, when you add or remove translatable strings in `_()` you should also run `genpot`, otherwise the activity maintainer will have to do it later.

**Comment by quozl** [comment]
@Aniket21mathur, thanks, I see what you mean.  We balance the human time spent maintaining the word lists against the computer time spent accessing files.  We don't have reliable information on how frequently school teachers may change the word lists.  The activity also has a feature for selecting a word list on media, and this may reduce need to change the built-in word lists.  As the activity is mostly in Spanish, I don't fully understand it.

I'm not willing to make a final decision.  Thanks for asking.  :grin:

**Comment by Aniket21mathur** [comment]
@quozl I think It would be better to compromise the computer time against the human time.And also importing and reading a file twice will not have a significant impact on computer timing and performance.
Thanks for giving your suggestions and views, I have changed the code according to your comment


> An alternative may be to use the first line of a word list as the category name.

now by which I totally agree. :smile: and which is my conclusive opinion also.
Thanks for reviewing!

**Comment by quozl** [comment]
@Aniket21mathur, please also make further changes.  In reviewing, this is what I found;
* `_archivo_sugar` copies the original files from the installed directory (`/usr/share/sugar/activities/Sindiente.activity` or `~/Activities/Sindiente.activity`) to the user's activity instance data directory (`.sugar/default/org.laptop.Sindiente/data`); why it does this is unclear,
* `palabra_aleatoria` does not ignore the first line that you added,
* `palabra_aleatoria` is asked to read from the copied files, yet `__init__` reads from the original files,
* `importar_lista_p` can write to the files.

I'm still struggling to understand how this activity is supposed to work, because I don't read Spanish, the buttons don't use icons, and pasting Python code into Google Translate tends to be unreliable.

**Comment by Aniket21mathur** [comment]
> _archivo_sugar copies the original files from the installed directory (/usr/share/sugar/activities/Sindiente.activity or ~/Activities/Sindiente.activity) to the user's activity instance data directory (.sugar/default/org.laptop.Sindiente/data); why it does this is unclear,
Whenever the user first runs the activity on his machine the files are written from the installed directory into the data directory ".sugar/default/org.laptop.Sindiente/data" and then the files are always read from the data directory.What we are doing currently in this pull request is that we are directly reading files from the installed directory fro the titles rather than reading it from the user's activity instance data directory.

>         categoria_nivel_1 = open('resources/nivel1.palabra')
        palabras_nivel_1 = categoria_nivel_1.readlines()
        palabras_nivel_1 = map(lambda s: s.strip(), palabras_nivel_1)

> palabra_aleatoria does not ignore the first line that you added,
Agreed, I will fix that.Thanks!

> importar_lista_p can write to the files.
Yes, writes the files into the user's activity instance data directory!
Thanks for reviewing! :smile:

**Comment by quozl** [comment]
> Whenever the user first runs the activity on his machine the files are written from the installed directory into the data directory ".sugar/default/org.laptop.Sindiente/data" and then the files are always read from the data directory. What we are doing currently in this pull request is that we are directly reading files from the installed directory from the titles rather than reading it from the user's activity instance data directory.

Yes, I saw that.  But I don't know why the activity is caching the files in the user's activity instance data directory.  Do you know?  If it is to support customisation, then the code should read the titles from there rather than the the installed directory.  If there is no reason, the copying should be removed.

**Comment by pro-panda** [comment]
@Aniket21mathur 
Will you be continuing to work on this ?

**Comment by Aniket21mathur** [comment]
>  If it is to support customisation, then the code should read the titles from there rather than the the installed directory

@quozl , yes I agree with you and hence made the code to read files from user's activity instance data.

**Pull request merged**
