### PR TITLE
Port to Python 3

### PR DESCRIPTION
**Pull request by Aniket21mathur**
Porting the activity code to Python 3.
Tested with Sugar v 0.114.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  I plan to merge after release of 0.114.

**Comment by Aniket21mathur** [comment]
Sure. Thanks!

**Comment by Aniket21mathur** [comment]
@quozl . Can we merge now? Thanks!

**Comment by quozl** [comment]
I'd like to test first, and I can't do a genuine test without the port to TelepathyGLib.

**Comment by Aniket21mathur** [comment]
Tested with toolkit (HEAD).
Thanks!

**Comment by quozl** [comment]
It doesn't work.  What is your test case?

Not sure if this is a cause, but logs contained;

```log
1566202174.310797 WARNING sindiente-activity: ['palomas', 'hago un nido, llevo mensajes, y me gusta estar en los parques.', 'es una de las aves que mas rapido vuela.\n']
Traceback (most recent call last):
  File "/usr/share/sugar/activities/Sindiente.activity/activity.py", line 612, in _nuevojuego_btn_clicked_cb
    self._creacion()
  File "/usr/share/sugar/activities/Sindiente.activity/activity.py", line 443, in _creacion
    self.palabra = str(contenido[0], "utf-8")
TypeError: decoding str is not supported

```

**Comment by Aniket21mathur** [comment]
> It doesn't work. What is your test case?

Thanks for testing. I think my test case was not that strong. I have fixed it in a new commit please review.

**Comment by quozl** [comment]
Thanks.  Please resolve conflicts; they seem related to your flake8 fixes two months ago.

**Comment by Aniket21mathur** [comment]
I rebased it with master. Thanks!

**Pull request merged**
