### PR TITLE
Adding and Updating Readme

### PR DESCRIPTION
**Pull request by Aniket21mathur**
The activity doesn't had a readme file.

Now adding readme to the activity and updating it.

Fixes https://github.com/sugarlabs/sin-dientes-activity/issues/6

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@quozl Can you please review it and have a look into "How to integrate" part.Thanks!

**Comment by quozl** [comment]
Thanks.  Reviewed.

* [ ] you change style of headings; _Reporting Bugs_ and _Contributing_ are set now as subheadings, they should be equal headings.

I've no comment to make about _How to integrate?_.

**Comment by Aniket21mathur** [comment]
@quozl .So we should not add "how to integrate" for this activity?I am not aware of exact dependencies of the activity so I left that part.Thanks!

**Comment by quozl** [comment]
@Aniket21mathur, look at other activity README.md files; we have many of them.  As a Python program the first dependency is Python, and you can find the dependencies by searching for Python `import` statements.  Then for each import determine if the module imported;
* is part of the Python standard distribution, e.g. `os`, then do not list it,
* is internal to the activity, then do not list it,
* has an external project name, list it, e.g. `gtk` is _GTK+ 2_,
* is internal to Sugar Labs, list the component name, e.g. `sugar` is _Sugar Toolkit for GTK+ 2_.

Honestly though, your work on the README.md file is of little benefit while #1 is open .  The activity cannot be run on modern Linux distributions because of #1.

**Comment by Aniket21mathur** [comment]
Thanks @quozl.I am working on issue #1 and will soon make a pull request having reference of it and then we will complete this pull request.

**Comment by Aniket21mathur** [comment]
@quozl after merging #8 this pull request can also be completed.
Thanks!

**Pull request merged**
